#add
POST http://localhost:8000/cinemas
Content-Type: application/json

{
  "name": "ArenaSofia",
  "address": "Sofia",
  "city_id": "1",
  "phone_number": "0888222223"
}
###
#filter
POST http://localhost:8000/cinemas/filter
Content-Type: application/json

{
  "city_id": 1,
  "projection_id": 5
}
###
#edit
PUT http://localhost:8000/cinemas/{id}
Content-Type: application/json

{
"name": "string",
"address": "string",
"city_id": "integer",
"phone_number": "string"
}
###
#gitById
GET http://localhost:8000/cinemas/{id}
Accept:  application/json
###
#getAll
GET http://localhost:8000/cinemas/all
Accept:  application/json
###
#remove
DELETE http://localhost:8000/cinemas/{id}
Accept:  application/json