# register user
POST http://localhost:8000/users
Content-Type: application/json

{
  "first_name": "Gosho",
  "last_name": "Petrov",
  "email": "goshko@abv.bg",
  "password": "1234",
  "confirmPassword":"1234",
  "birth_date": "2000-12-01",
  "city_id": 1,
  "gender": "m",
  "phone_number": "0888888888",
  "role_name": "user"
}
###
# login user
POST http://localhost:8000/users/login
Content-Type: application/json

{
  "email": "string",
 "password": "string"

}
###
# logout user
POST http://localhost:8000/users/logout
Content-Type: application/json
###
#  change password
POST http://localhost:8000/users
Content-Type: application/json

{
 "currentPassword": "ani@abv.bg",
 "newPassword": "pass1234",
 "confirmNewPassword": "pass1234"


}
###
# edit profile
PUT http://localhost:8000/users
Content-Type: application/json

{
  "first_name": "string",
  "last_name": "string",
  "email": "string",
  "password": "string",
  "birth_date": "date",
  "city_id": "integer",
  "gender": "string",
  "phone_number": "string",
  "role_name": "string"
}


###
# get user by id
GET http://localhost:8000/users/1
Content-Type: application/json


