# register user
POST http://localhost:8000/users
Content-Type: application/json

{
  "first_name": "Masho",
  "last_name": "Marov",
  "email": "mashko@abv.bg",
  "password": "123456Sa#",
  "confirmPassword":"123456Sa#",
  "birth_date": "2000-12-01",
  "city_id": 1,
  "gender": "m",
  "phone_number": "0888888888",
  "role_name": "user"
}
###
# login user
POST http://localhost:8000/users/login
Content-Type: application/json

{

  "email": "mashko@abv.bg",
 "password": "123456Sa#"

}
###
# logout user
POST http://localhost:8000/users/logout
Content-Type: application/json
###
#  change password
POST http://localhost:8000/users
Content-Type: application/json

{
 "currentPassword": "123456Sa#",
 "newPassword": "12345RRrr*",
 "confirmNewPassword": "12345RRrr*",
  "email": "mashko@abv.bg"

}
###
# edit profile
PUT http://localhost:8000/users
Content-Type: application/json

{
  "first_name": "string",
  "last_name": "string",
  "email": "string",
  "password": "string",
  "birth_date": "date",
  "city_id": "integer",
  "gender": "string",
  "phone_number": "string",
  "role_name": "string"
}


###
# get user by id
GET http://localhost:8000/users/3
Content-Type: application/json


