# register user
POST http://localhost:8000/users
Content-Type: application/json

{
  "first_name": "Admin2",
  "last_name": "Parov",
  "email": "admin2@abv.bg",
  "password": "123456Sb#",
  "confirmPassword":"123456Sb#",
  "birth_date": "2000-12-01",
  "city_id": 1,
  "gender": "m",
  "phone_number": "0888888855",
  "role_name": "ADMIN"
}
###
# login user
POST http://localhost:8000/users/login
Content-Type: application/json

{
  "email": "admin2@abv.bg",
  "password": "123456Sb#"


}
###
# login user
POST http://localhost:8000/users/login
Content-Type: application/json

{
"email": "example123@example.com",
"password": "Passw0rd!"
}
###
# logout user
POST http://localhost:8000/users/logout
Content-Type: application/json

###
#  change password
PUT http://localhost:8000/users
Content-Type: application/json

{
 "currentPassword": "123456Sb#",
 "newPassword": "12345RRrr*",
 "confirmNewPassword": "12345RRrr*",
  "email": "mashko@abv.bg"

}
###
# edit profile
PUT http://localhost:8000/users/edit
Content-Type: application/json

{
  "first_name": "Boris",
  "last_name": "Parov",
  "email": "boris@abv.bg",
  "password": "123456Sb#",

  "birth_date": "2000-12-01",
  "city_id": 1,
  "gender": "m",
  "phone_number": "0888888811",
  "role_name": "ADMIN"
}


###
# get user by id
GET http://localhost:8000/users/12
Content-Type: application/json


###
# login user
POST http://localhost:8000/users/login
Content-Type: application/json

{
  "email": "chloesmith@abv.bg",
  "password": "123456Sb#"
}

###
# edit profile
PUT http://localhost:8000/users/edit
Content-Type: application/json

{
  "id": 12,
  "first_name": "Chloe",
  "last_name": "Smith",
  "email": "chloesmith@abv.bg",
  "birth_date": "1989-12-12",
  "city_id": 2,
  "gender": "F",
  "phone_number": "9876543210",
  "role_name": "USER"
}


